### ISSUE TITLE
Pre-approve request API has error response.

### ISSUE THREAD

**Issue by kidylee** [nrahnemoon/AirbnbAPIBlog#2]
First of all, thanks for your hard work to publish and maintain this document.
Recently I'm developing an App for internal usage around Airbnb API, everything is great except the pre-approve API. The reject is working fine, but the pre-approve give me below response:

```
{
  "error_code": 400,
  "error": "validation",
  "error_message": "Your request could not be completed because of the following errors: The preapproval dates are not available."
}
```

I've double checked that the date is available and tried multiple request, but the issue still there. Do you have any advise? Thanks.

**Comment by kidylee** [comment]
Sorry, My fault, I was pre-approving a pending status.

**Comment by nrahnemoon** [comment]
Ah gotcha.
